name = kanis_materials
description = Adds custom materials (Kanilite, Hachilite, Momongaite, Ignitz) with Mineclonia and Melterns integration.
depends = default, melterns
optional_depends = mineclonia, mcl_core, mcl_worlds
